name: Feature Engineering

on:
  workflow_dispatch:

jobs:
  run-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data fetching script
        run: python data_fetching.py
